# Generated by Django 5.1.1 on 2024-10-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtasks',
            name='generated_by_ai',
            field=models.BooleanField(default=False),
        ),
    ]
