# Generated by Django 5.1.1 on 2024-11-12 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_blockedsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedsite',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 12, 6, 59, 51, 537268, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='/staticfiles+==/images/defaultuserimage.png', upload_to='uploads'),
        ),
    ]
