# Generated by Django 5.1.1 on 2024-11-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blockedsite_expiration_alter_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockedsite',
            name='expiration',
        ),
        migrations.AddField(
            model_name='blockedsite',
            name='duration',
            field=models.IntegerField(default=60),
        ),
    ]
