# Generated by Django 5.1.1 on 2024-11-16 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_blockedsite_expiration_blockedsite_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtasks',
            name='generated_by_ai',
        ),
        migrations.RemoveField(
            model_name='subtasks',
            name='timeframe',
        ),
        migrations.AddField(
            model_name='goals',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtasks',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtasks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
