# Generated by Django 5.1.1 on 2024-11-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_subtasks_generated_by_ai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtasks',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='/staticfiles/images/defaultuserimage.png', upload_to='uploads'),
        ),
    ]
