# Generated by Django 5.1.1 on 2024-12-02 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_subtasks_created_at_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedsite',
            name='blocked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
