# Generated by Django 5.1.1 on 2024-12-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_blockedsite_blocked_at_dashboard_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='task_management',
            field=models.CharField(choices=[('Single Task', 'Single Task'), ('Multi-tasking', 'Multi-tasking')], default='Single Task', max_length=40),
        ),
    ]
