# Generated by Django 5.1.2 on 2025-01-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_preferences_task_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='time_of_day',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], default='Morning', max_length=50),
        ),
    ]
