# Generated by Django 4.2.17 on 2024-12-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_preferences_task_management'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtasks',
            old_name='tasks',
            new_name='goal',
        ),
        migrations.AlterUniqueTogether(
            name='blockedsite',
            unique_together={('user', 'url')},
        ),
    ]
