# Generated by Django 4.2.17 on 2025-01-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_preferences_time_of_day'),
        ('api', '0010_rename_tasks_subtasks_goal_and_more'),
    ]

    operations = [
    ]
