# Generated by Django 4.2.17 on 2025-01-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_subtasks_end_time_alter_preferences_sound_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='time_of_day',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], default='Morning', max_length=50),
        ),
    ]
